# -*- coding: utf-8 -*-
"""hw2-q3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1svKZKYsI34pCwu5lLY52NbijFlMyYx22
"""

from keras.datasets import mnist
from keras.utils import np_utils
import numpy as np

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train = x_train.reshape((60000, 784))
x_test  = x_test.reshape ((10000, 784))

x_train = x_train.astype('float32')
x_test  = x_test.astype ('float32')

x_train /= 255
x_test  /= 255

y_train = np_utils.to_categorical(y_train)
y_test  = np_utils.to_categorical(y_test)

from sklearn.neural_network import BernoulliRBM

rbm = BernoulliRBM(n_components=100, learning_rate=0.01, batch_size=32, n_iter=10, verbose=True, random_state=None)
rbm.fit(x_train)
train=rbm.transform(x_train)
test=rbm.transform(x_test)

from keras.layers import Input, Dense
from keras.models import Sequential
from keras.models import Model

net = Sequential()
net.add(Dense(512, activation = 'relu', input_dim=100, kernel_initializer='normal'))
net.add(Dense(512, activation  = 'relu'))
net.add(Dense(10 , activation  = 'softmax'))

from keras import optimizers

sgd = optimizers.SGD(lr=0.01)
net.compile(optimizer=sgd, loss='categorical_crossentropy', metrics=['accuracy'])
net.summary()

import timeit

start = timeit.default_timer()

trained_model = net.fit(train, y_train, batch_size = 32, epochs = 30, validation_split = 0.2)
history = trained_model.history

stop = timeit.default_timer()
print('Time: ', stop - start)