# -*- coding: utf-8 -*-
"""hw1-q4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ns7993BTlZw1E7DsHvHG9OLGyNLQWASb
"""

import numpy as np

x = np.array([ 0,  3,   4,  -1])
y = np.array([ 2,  2,  -2,  -2])

w_x = np.array([  0,    4,   0,  -4])
w_y = np.array([  1,    1,   1,   1])
b   = np.array([ -2,  -14,   2,  -2])

w_and = np.ones(4)
b_and = -4

def line(x, y, w_x, w_y, b):
  net = w_x * x + w_y * y + b
  if net <= 0:
    return True
  else:
    return False
  
def convex(x, y):
  a_line = line(x, y,  w_x[0],  w_y[0],  b[0])
  b_line = line(x, y,  w_x[1],  w_y[1],  b[1])
  c_line = line(x, y, -w_x[2], -w_y[2],  -b[2])
  d_line = line(x, y,  w_x[3],  w_y[3],  b[3])
  
  out = a_line + b_line + c_line + d_line + b_and
  if out >= 0 :
    return True
  else:
    return False

def input_(a, b):
  if convex(a, b)==True:
    print("(",a,",",b,")","IS inside of the convex polygon.")
    plt.plot(a, b, 'bo')
  else:
    print("(",a,",",b,")","ISN'T inside of the convex polygon.")
    plt.plot(a, b, 'ro')

import matplotlib.pyplot as plt

x_line1 = np.linspace( 0,  3, 500)
y_line1 = np.linspace( 2,  2, 500)
plt.plot(x_line1, y_line1, 'blue')

x_line2 = np.linspace( 3,  4, 500)
y_line2 = np.linspace( 2, -2, 500)
plt.plot(x_line2, y_line2, 'blue')

x_line3 = np.linspace( 4, -1, 500)
y_line3 = np.linspace(-2, -2, 500)
plt.plot(x_line3, y_line3, 'blue')

x_line4 = np.linspace(-1,  0, 500)
y_line4 = np.linspace(-2,  2, 500)
plt.plot(x_line4, y_line4, 'blue')
plt.xlabel('x')
plt.ylabel('y')

#inside
input_( 1,   1)
input_( 3,-1.5)
input_( 1, 1.5)
input_( 0,   0)
input_( 2, 1.5)
input_( 2,   2)
input_( 0,   1)
#outside
input_(4 ,-2.1)
input_(-2,   0)
input_(-3,   0)
input_(-1, 0.5)
input_(4 ,   2)
input_(5 ,  -1)
input_(4.5,1.5)

plt.show()