# -*- coding: utf-8 -*-
"""hw4-q2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15hXv0bfhb4dfyoXcMpkk-vZySdpZuY7Y
"""

import numpy as np

sample = np.matrix([ 1,  1, -1,  1, -1,  1, -1,  1,  1,  1,  1]) #sick
# sample = np.matrix([-1,  1, -1, -1, -1,  1, -1,  1, -1,  1, -1]) #not sick

m = np.zeros([2, 11])
m[0] = np.matrix([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])
m[1] = np.matrix([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

w = np.zeros([11, 2])
w[:,0] = 0.5 * m[0]
w[:,1] = 0.5 * m[1]
w

b = 11/2

y = np.zeros([2, 1])

y[0] = b + np.matmul(sample, w[:,0])
y[1] = b + np.matmul(sample, w[:,1])
# print(y[0])
# print(y[1])

input_ = y.flatten()

def relu(x):
  if x >= 0:
    return x
  else:
    return 0

e = 0.4
net = 0
output = np.zeros(2)

flag = True
index = 0;
while(flag):
  for i in range (0, 2):
    output[i] = input_[i] - e * (input_[0] + input_[1] - input_[i])
  for i in range (0, 2):
   output[i] = relu(output[i])
  input_ = output.copy()
  if output[0] == 0:
    index = 1
    flag = False
  if output[1] == 0:
    flag = False
    index = 0

print('sample is :',sample)
print('MaxNet input is:',y.reshape(1,2))
print('MaxNet output/HammingNet output is',output)
if index==0:
  print('she/he is ok.')
else:
  print('she/he is sick.')


# + str(index)